#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Redirect stdin to /dev/tty only when available (allows non-interactive environments)
[ -e /dev/tty ] && exec < /dev/tty || true

echo "1. Running Typecheck..."
yarn typecheck || exit 1

echo "2. Running Lint-Staged..."
yarn lint-staged || exit 1

echo "3. Running Tests..."
yarn test --passWithNoTests || exit 1
