#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

exec < /dev/tty

echo "1. Running Typecheck..."
yarn typecheck || exit 1

echo "2. Running Lint-Staged..."
npx lint-staged || exit 1

echo "3. Running Tests..."
yarn test --passWithNoTests || exit 1
